class Solution(object):
    def networkDelayTime(self, times, n, k):
        """
        :type times: List[List[int]]
        :type n: int
        :type k: int
        :rtype: int
        """

        dic = {}
        for time in times:
            if dic.has_key(time[0]):
                dic[time[0]].append(time)
            else:
                dic[time[0]] = [time]

        visied = {k:0}
        def dfs_network(u):
            if not dic.has_key(u):
                return
            for time in dic[u]:
                # time[0] 就不用额外赋值了，它就是 u
                v, w = time[1], time[2]
                if visied.has_key(v):
                    visied[v] = min(visied[u] + w, visied[v])
                else:
                    visied[v] = visied[u] + w
                dfs_network(time[1])
        
        dfs_network(k)
        if len(visied) < n:
            return -1
        return max(visied.values())
        
"""
https://leetcode-cn.com/submissions/detail/202191183/

3 / 52 个通过测试用例
状态：执行出错

执行出错信息：
RuntimeError: maximum recursion depth exceeded in cmp
    visied[v] = min(visied[u] + w, visied[v])
Line 25 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network(time[1])
Line 28 in dfs_network (Solution.py)
    dfs_network... 12074 more chars
最后执行的输入：
[[1,2,1],[2,1,3]]
2
2
"""
"""
我从未见过有如此——长的RE报错信息。。。
"""
